### ISSUE TITLE
Novo repositório com as texturas

### ISSUE THREAD

**Issue by AndersonAlcara** [AndersonAlcara/Game-Alg-Prog-UFRGS#1]
Olá @htrein, espero que vc aceite ser colaborador do projeto que maior parte vc fez.

**Comment by htrein** [comment]
Oi @AndersonAlcara , claro! Porém o convite expirou, poderia mandar novamente?

**Comment by AndersonAlcara** [comment]
Claro @htrein, já enviei novamente :). Após, vou fechar issue, um abraço.
